// Generated by CoffeeScript 1.6.2
var crController, http, url;

http = require('http');

url = require('url');

crController = require("chapp/chat_room_controller");

module.exports = http.createServer(function(req, res) {
  var controller;

  if (url.parse(req.url).pathname === "/comet") {
    controller = crController.create(req, res);
    return controller[req.method.toLowerCase()]();
  }
});
