// Generated by CoffeeScript 1.6.2
var chatRoomController, expect;

expect = require('chai').expect;

chatRoomController = require('../../lib/chapp/chat_room_controller');

describe("chatRoomController", function() {
  return it("should be an object", function() {
    return expect(chatRoomController).to.be.an('object');
  });
});
