// Generated by CoffeeScript 1.6.2
var chatRoomController, testCase;

testCase = require("nodeunit").testCase;

chatRoomController = require('../../lib/chapp/chat_room_controller');

exports.testchatRoomController = function(test) {
  test.isNotNull(chatRoomController);
  test.isFunction(chatRoomController.create);
  return test.done();
};
