// Generated by CoffeeScript 1.6.2
var Q, chatRoom;

require("./function-bind");

Q = require('q');

chatRoom = {
  addMessage: function(user, msgtext) {
    var deferred;

    deferred = Q.defer();
    process.nextTick((function() {
      var err, id, message, _ref;

      if (!user) {
        err = new TypeError("user is null");
      }
      if (!msgtext) {
        err = new TypeError("Message text is null");
      }
      if (err) {
        deferred.reject(err);
      }
      if (!err) {
        if ((_ref = this.messages) == null) {
          this.messages = [];
        }
        id = this.messages.length + 1;
        message = {
          id: id,
          user: user,
          msgtext: msgtext
        };
        this.messages.push(message);
        return deferred.resolve(message);
      }
    }).bind(this));
    return deferred.promise;
  },
  getMessagesSince: function(id, callback) {
    var deferred, _ref;

    deferred = Q.defer();
    if ((_ref = this.messages) == null) {
      this.messages = [];
    }
    process.nextTick((function() {
      return deferred.resolve(this.messages.slice(id));
    }).bind(this));
    return deferred.promise;
  }
};

module.exports = chatRoom;
