// Generated by CoffeeScript 1.6.2
var chatRoomController;

require("./function-bind");

chatRoomController = {
  create: function(request, response) {
    return Object.create(this, {
      request: {
        value: request
      },
      response: {
        value: response
      }
    });
  },
  post: function() {
    var body;

    body = "";
    this.request.addListener("data", function(chunk) {
      return body += chunk;
    });
    return this.request.addListener("end", (function() {
      var data,
        _this = this;

      data = JSON.parse(decodeURI(body)).data;
      return this.chatRoom.addMessage(data.user, data.message).then(function() {
        _this.response.writeHead(201);
        return _this.response.end();
      }).done();
    }).bind(this));
  }
};

module.exports = chatRoomController;
