// Generated by CoffeeScript 1.6.2
var chatRoomController;

chatRoomController = {
  create: function(request, response) {
    return Object.create(this, {
      request: {
        value: request
      },
      response: {
        value: response
      }
    });
  }
};

module.exports = chatRoomController;
