// Generated by CoffeeScript 1.6.2
var chatRoom;

chatRoom = {
  addMessage: function(user, msgtext, callback) {
    var err, message, _ref, _ref1;

    if (!user) {
      err = new TypeError("user is null");
    }
    if (!msgtext) {
      err = new TypeError("Message text is null");
    }
    if (!err) {
      if ((_ref = this.id) == null) {
        this.id = 1;
      }
      message = {
        id: this.id++,
        user: user,
        msgtext: msgtext
      };
      if ((_ref1 = this.messages) == null) {
        this.messages = [];
      }
      this.messages.push(message);
    }
    if (typeof callback === "function") {
      return callback(err, message);
    }
  },
  getMessagesSince: function(id, callback) {
    return callback(null, this.messages.slice(id));
  }
};

module.exports = chatRoom;
