// Generated by CoffeeScript 1.6.2
if (!Function.prototype.bind) {
  (function() {
    var slice;

    slice = Array.prototype.slice;
    return Function.prototype.bind = function(thisObj) {
      var args, target;

      target = this;
      if (arguments.length > 1) {
        args = slice.call(arguments, 1);
        return function() {
          var allArgs;

          allArgs = args;
          if (arguments.length > 0) {
            allArgs = args.concat(slice.call(arguments));
          }
          return target.apply(thisObj, allArgs);
        };
      }
      return function() {
        if (arguments.length > 0) {
          target.apply(thisObj, arguments);
        }
        return target.call(thisObj);
      };
    };
  })();
}
