// Generated by CoffeeScript 1.6.2
var chatRoom, crController, http, room, url;

http = require('http');

url = require('url');

crController = require("./chat_room_controller");

chatRoom = require("./chat_room");

room = Object.create(chatRoom);

module.exports = http.createServer(function(req, res) {
  var controller;

  if (url.parse(req.url).pathname === "/comet") {
    controller = crController.create(req, res);
    controller.chatRoom = room;
    return controller[req.method.toLowerCase()]();
  }
});
