// Generated by CoffeeScript 1.6.2
module.exports = function(returnValue) {
  var stub;

  stub = function() {
    stub.called = true;
    stub.args = arguments;
    stub.thisArg = this;
    return returnValue;
  };
  stub.called = false;
  return stub;
};
